import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";

import Nav from "./components/Nav";
import Footer from "./components/Footer";
import Provider from "./components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${inter.className}`}>
        <Provider>
          <div className="w-full bg-gradient-to-br from-indigo-50 via-white to-cyan-100">
            <div className="container mx-auto p-5 ">
              <Nav />
              <div className="pt-8">{children}</div>
              <Footer />
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
